export const links = [
    { url: '/', name: 'Home' },
    { url: '/library', name: 'Library' },
    { url: '/cart', name: 'Cart' },
    { url: '/history', name: 'History' },
]

export const books = [
    { name: 'Betty', image: '/assets/Images/first.jpg', pages: 300, author: 'Tiffany Mcdaniel',summary:"A girl comes of age against the knife" ,description: '"A girl comes of age against the knife." So begins the story of Betty Carpenter. Born in a bathtub in 1954 to a Cherokee father and white mother, Betty is the sixth of eight siblings. The world they inhabit is one of poverty and violence--both from outside the family, and also, devastatingly, from within. The lush landscape, rich with birdsong, wild fruit, and blazing stars, becomes a kind of refuge for Betty, but when her family’s darkest secrets are brought to light, she has no choice but to reckon with the brutal history hiding in the hills, as well as the heart-wrenching cruelties and incredible characters she encounters in her rural town of Breathed, Ohio. ' },
    { name: 'Arabia Felix', image: '/assets/Images/second.jpg', pages: 400, author: 'Thorkild Hansen',summary:"Arabia Felix is the spellbinding true story of a scientific expedition gone disastrously awry", description: 'Arabia Felix is the spellbinding true story of a scientific expedition gone disastrously awry. On a winter morning in 1761 six men leave Copenhagen by sea—a botanist, a philologist, an astronomer, a doctor, an artist, and their manservant—an ill-assorted band of men who dislike and distrust one another from the start. These are the members of the Danish expedition to Arabia Felix, as Yemen was then known, the first organized foray into a corner of the world unknown to Europeans. The expedition made its way to Turkey and Egypt.' },
    { name: 'La Casa Della Moschea', image: '/assets/Images/third.jpg', pages: 200, author: 'Kader Abdolah',summary:"The epic of an influential Persian family whose destinies are intertwined", description: 'The epic of an influential Persian family whose destinies are intertwined with the history of its people, a saga that makes you experience from the inside and understand the crucial transformations of a country at the center of world balances, in the years that go from the landing on Moon at the end of the war with Iraq, from the Shah’s regime to post-Khomeini."I wrote this text for Europe" says Kader Abdolah. “I pulled back the veil to show Islam as a way of life… a moderate, domestic Islam, not the radical one.”' },
    { name: 'Over The Sirens', image: '/assets/Images/fourth.jpg', pages: 400, author: 'Zelda Riese',summary:'Get ready to fall in love with "Over the Sirens"', description: 'Get ready to fall in love with "Over the Sirens", a contemporary romance novel that is sure to pull at your heartstrings. Meet Scarlett, a struggling actress who has just experienced a family tragedy and is feeling lost in a world without her parents. She’s searching for direction and wants to make a change, but feels alone in her journey. Enter Graham, a former paramedic badly injured on the job and now working as a bartender. He’s pushed away his friends and family, desperately wanting his old life back, but feels disconnected and alone. When they meet at his bar, they realize they have a connection and go on a journey together to find peace with their lives.' },
    { name: 'The Great Gatsby', image: '/assets/Images/fifth.jpg', pages: 150, author: 'F.Scott Fitzgerald',summary:'The Great Gatsby, F. Scott Fitzgerald’s third book', description: 'The Great Gatsby, F. Scott Fitzgerald’s third book, stands as the supreme achievement of his career. First published in 1925, this quintessential novel of the Jazz Age has been acclaimed by generations of readers. The story of the mysteriously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan, of lavish parties on Long Island at a time when The New York Times noted “gin was the national drink and sex the national obsession,” it is an exquisitely crafted tale of America in the 1920s.' },
    { name: 'The MindFulness Journal', image: '/assets/Images/sixth.jpg', pages: 200, author: 'Corinne Sweet',summary:'Mindfulness is a simple and powerful practice that can help you cut through the noise and reclaim tranquillity', description: ' In today’s busy world, finding physical and mental space for peace and calm amidst the competing demands of work, family and friends can be a challenge. Mindfulness is a simple and powerful practice that can help you cut through the noise and reclaim tranquillity, wherever you are. The Mindfulness Journal offers an introduction to mindfulness and easy exercises that can be done whether you are sitting at your desk, squeezed on to a crowded train, or standing in line at the supermarket. Beautifully illustrated, with notes pages to record your thoughts, this journal is your indispensable companion to a more peaceful, stress-free day. ' },
    // { name: 'Stories In The Stars', image: '/Images/Books/Stories In The Stars.jpg', pages: 361, author: 'Susanna Hislop', description: 'To those who can decipher it, the night sky is alive with gods and goddesses, animals and mythical creatures—an endless carnival played out in shining constellations. Amidst this jet-black canvas pricked with white dots, a hunter leaps in pursuit with his dogs at his heels, a sea monster threatens a maiden in distress, and a pair of twins lives forever.In Stories in the Stars, writer and stargazer Susanna Hislop and international artist Hannah Waldron present an imaginative journey through the heavens. Leaping between centuries, cultures, and traditions, they explore each of the night sky’s eighty-eight constellations through gorgeous illustrations and vivid descriptions that will linger in readers’ minds long after they’ve closed the book and stepped outside on a starry night.' },
    // { name: 'The Periodic Table', image: '/Images/Books/The Periodic Table.jpg', pages: 266, author: 'Primo Levi', description: 'The Periodic Table is largely a memoir of the years before and after Primo Levi’s transportation from his native Italy to Auschwitz as an anti-Facist partisan and a Jew.It recounts, in clear, precise, unfailingly beautiful prose, the story of the Piedmontese Jewish community from which Levi came, of his years as a student and young chemist at the inception of the Second World War, and of his investigations into the nature of the material world. As such, it provides crucial links and backgrounds, both personal and intellectual, in the tremendous project of remembrance that is Levi’s gift to posterity. But far from being a prologue to his experience of the Holocaust, Levi’s masterpiece represents his most impassioned response to the events that engulfed him.The Periodic Table celebrates the pleasures of love and friendship and the search for meaning, and stands as a monument to those things in us that are capable of resisting and enduring in the face of tyranny.' },
    // { name: 'Turbulence', image: '/Images/Books/Turbulence.jpg', pages: 184, author: 'David Szalay', description: 'From the acclaimed, Man Booker Prize-shortlisted author of All That Man Is, a stunning, virtuosic novel about twelve people, mostly strangers, and the surprising ripple effect each one has on the life of the next as they cross paths while in transit around the world.A woman strikes up a conversation with the man sitting next to her on a plane after some turbulence. He returns home to tragic news that has also impacted another stranger, a shaken pilot on his way to another continent who seeks comfort from a journalist he meets that night. Her life shifts subtly as well, before she heads to the airport on an assignment that will shift more lives in turn.In this wondrous, profoundly moving novel, Szalay’s diverse protagonists circumnavigate the planet in twelve flights, from London to Madrid, from Dakar to Sao Paulo, to Toronto, to Delhi, to Doha, en route to see lovers or estranged siblings' },
    // { name: 'Simplicity', image: '/Images/Books/Simplicity.jpg', pages: 256, author: 'Gretchen Stewart', description: 'Simplicity is a philosophy. A way of life. A new way to think. A paradigm shift inducing global movement. In Simplicity, I break down the stresses of the modern age and help you curate your best life. We treat your existence as art and learn how to live with intention as well as increase your focus, despite all the demands and distractions of this era.' },
    // { name: 'Intuition', image: '/Images/Books/Intuition.jpg', pages: 388, author: 'Amisha Ghadiali', description: 'Tune into your senses, find your inner wisdom and develop your physical, mental, emotional and spiritual awareness. This self-help book will help you open yourself up to the power of intuition.Intuition is seen by many as the highest form of intelligence. It’s the ability to know something instinctively without having to discover it - a deep sense of knowing, that gut feeling. Your intuition can guide you to make wise decisions that bring more joy, love and meaning into your life.From journaling and meditation to mindful movement and moon rituals, this developmental guide taps into the myriad ways you can unlock intuitive living. It teaches you how to use a broad range of practices and techniques designed to reveal your path to innate wisdom.' },
    // { name: 'When You Ask Me When I’m Going', image: '/Images/Books/When You Ask Me When I’m Going.jpg', pages: 256, author: 'Jasmin ', description: 'screamso that one daya hundred years from nowanother sister will not have todry her tears wonderingwhere in historyshe lost her voiceThe six sections of the book explore what it means to be a young woman living in a world that doesn’t always hear her and tell the story of Kiran as she flees a history of trauma and raises her daughter, Sahaara, while living undocumented in North America.Delving into current cultural conversations including sexual assault, mental health, feminism, and immigration, this narrative of resilience, healing, empowerment, and love will galvanize readers to fight for what is right in their world.' },
]